version: "3"

services:
  instapibot:
    container_name: instapibot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped

  nginx:
    build: ./nginx
    restart: always
    container_name: instapibot-nginx
    env_file: .env
    environment:
      - VIRTUAL_HOST=${URL}
      - LETSENCRYPT_HOST=${URL}
      - LETSENCRYPT_EMAIL=${EMAIL_HOST_USER}
    depends_on:
      - instapibot

networks:
  default:
    external:
      name: proxy-bypass
